export const TEXTS = {
  INITIAL_TABLE_PAGE: 0,
  INITIAL_PAGE_ROWS: 5,
  INITIAL_COLLAPSED_PAGE_ROWS: 3,
  DEFAULT_ROWS_PER_PAGE_OPTION: [5, 10, 25],
  SEARCH_LABEL: 'Search...',
  DELETE_SELECTED: 'Delete Selected',
  SHOW_MORE: 'הצג יותר',
  SHOW_LESS: 'הצג פחות',
  EXPORT_TO_EXCEL_TITLE: 'ייצוא לאקסל',
  EXPORT_TO_EXCEL_EXPLANATION:
    'האם תרצה לייצא את האקסל בגרסה מסוננת לפי מה שבחרת בטבלה או את הגרסה המלא  עם כל הערביויות?',
  EXPORT_BY_FILTERS: 'ייצוא קובץ לפי הסינונים שלך',
  EXPORT_FULL_FILE: 'ייצוא קובץ מלא',
  DOWNLOAD_FILE: 'הורדת הקובץ',
  DOWNLOAD_BAIL: 'הורדת ערבות',
  EXTEND_BAIL: 'הארכת ערבות',
  BAIL_STATUS: 'סטטוס ערבות',
  ACTIVE_BAIL: ' ערבות פעילה',
  TYPE_ONE_BAIL: 'סוג ערבות',
  TYPE_TWO_BAIL: 'סוג ערבות נוסף',
  NON_ACTIVE_BAIL: 'ערבות לא פעילה',
  BAIL_TYPE: 'סוג ערבות',
  AVTIVE_BAILS: 'ערבויות פעילות',
  COIN_TYPE: 'סוג מטבע',
  FORIEN_COIN: 'מטבע זר',
  LOCAL_COIN: 'מטבע מקומי',
  CLEAN_ALL: 'נקה הכל',
  ALL_TYPES: 'כל הסוגים',
  FORMAL: 'פורמלית',
  MONETARY: 'כספית',
};

export const COLORS = {
  SUMMERY_ROW_WRAPPER: '#ffdbc3',
  TABLE_HEADER: 'gray',
  TABLE_SECONDARY: '#10829b',
  BUTTON_PRIMARY: '#5052e0',
};
